### ISSUE TITLE
Arrow like path

### ISSUE THREAD

**Issue by omidb** [andreaferretti/paths-scala-js#2]
Hi,
How can I draw a path with a arrow at the end? I'm trying to use your code in reactjs.

Thanks

**Comment by andreaferretti** [comment]
There is currently no way. I have never needed an arrow shape, so I did not think about adding one. I think it would be a nice thing to add for next version.

What you can do right now is to use the low level API. You see, every path has all SVG methods, so if you have an existing path `p`, you can do something like (check the API, I am writing from memory)

```
val js.Array(a, b) = p.points.last
val arrow = p.lineto(x1, y1).moveto(a, b).lineto(x2, y2)
```

where you have to figure out `x1`, `y1`, `x2` and `y2`.

Actually, what I would do for an arrow shape is exactly this, after having figured out the appropriate direction based on the shape of `p`.

**Comment by omidb** [comment]
How should I deal with orientation in a nice way?

**Comment by andreaferretti** [comment]
Well, this is the part where I say "where you have to figure out x1, y1, x2 and y2" :-P

It depends on the type of your path. Paths in SVG are composed by stringing together a number of primitives (essentially lines, ellipse arcs and bezier curves) and essentially the problem reduces to finding the slope at the end of the path, depending on the type and parameters of the last chunk.

The trivial case is of course that of lines. For the rest, I think they can be found explicitly, but I did not think much how exactly. It should be doable, though, given that one can one chunks like [smoothCurveTo](http://www.w3.org/TR/SVG/paths.html#PathDataCubicBezierCommands) that needs to attach smoothly to the previous arc

**Comment by omidb** [comment]
implementing SVG marker as paths.js would be a nice idea. because not all renderers has access to markers!
or even stroke properties like -dash,dot-

**Comment by andreaferretti** [comment]
This is best left as something to implement in the parent library, hence I am closing this ticket
