### ISSUE TITLE
A scala way to use path lowlevel

### ISSUE THREAD

**Issue by omidb** [andreaferretti/paths-scala-js#4]
Hi, thanks again for the Path,

I wanted to check what is a good way when given a list of point you want to add a path between them (curved, ... any lowlevel function)

I did this: where ps is a list of `(double,double)`

``` scala
val myPath = ps.sliding(2)
                  .foldLeft(Path())((pth,pnts) => {
          val p1 = pnts(0)
          val p2 = pnts(1)
          pth.qcurveto(p1._1, p1._2,p2._1, p2._2)
      }).closepath()
```

I tried this and I cannot see anything happening.

**Comment by andreaferretti** [comment]
You are almost there! :-)

The only thing that is missing is the `moveto` command, that position the pen somewhere. That has to be the first command, otherwise the SVG path does not have a starting point. Try

``` scala
val myPath = ps.sliding(2).foldLeft(Path().moveto(0, 0))((pth,pnts) => {
    val p1 = pnts(0)
    val p2 = pnts(1)
    pth.qcurveto(p1._1, p1._2,p2._1, p2._2)
}).closepath()
```

**Comment by omidb** [comment]
Thanks :)
I was trying to draw cpettitt/dagre#181 , I used bezier and it a little bit too curvy, what do you suggest?

**Comment by andreaferretti** [comment]
It seems that the control points are a little off. Otherwise, bezier should work fine

**Comment by omidb** [comment]
can I control Bezier curvature ?

**Comment by andreaferretti** [comment]
Sure, just use `curveto` in place of `qcurveto` http://www.w3.org/TR/SVG/paths.html#PathDataCubicBezierCommands

**Comment by omidb** [comment]
I wish it was easier to use, something like d3 line that you can adjust the curvature.

**Comment by andreaferretti** [comment]
Sorry about the delay, maybe it is too late for your use case, but still...

By design, the low level API of Paths.js matches the SVG path specification verbatim. It seems that what you need is some kind of Shape that takes some geometric parameters, such as curvature, and outputs a suitable path, maybe composed of Bezier curves. Do you have some concrete API in mind that you think makes sense?
